version: "3"

services:
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: mordiate4
      MYSQL_DATABASE: wikiplante
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - my-network
  wikiplante-api:
    build: .
    restart: always
    ports:
      - "3001:3001"
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - db 
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_USER: root
      DB_PASSWORD: mordiate4
      DB_DATABASE: wikiplante
    networks:
      - my-network

volumes:
  db_data:

networks:
  my-network:
